# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3701986fcee7ce8c5bd7255f98e5082914808a6a8070b1b8525d1bd14976aa1c3b78879f933652be9ecabca54924066781af571272de80f9a375c89b14f0dbbd

test:
  secret_key_base: e37a4ea7a18bee2c8816fff3833fec4e780497d91c38454aaa70843e13d19797d6de195d32f82c7ff81ff7128e393a23cd35ed5178ed3e45960ebcfdff24d4d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
